service: cmr-stac-api

provider:
  name: aws
  runtime: nodejs10.x
  stage: dev
  region: us-east-1

functions:
  search-api:
    handler: lib/application.handler
    events:
      - http:
          path: /
          method: GET
      - http:
          path: /{proxy+}
          method: any

plugins:
  - serverless-offline
